[network]
port  = ":8080"

[authenticator]
secret ="hello!!!"
account = ""
issuer = "test"
fileName = "qr.PNG"

[db]
database = "mysql"
url = "root:root@tcp(localhost:3306)/Scrapping?multiStatements=true&parseTime=true"